// AUTO-GENERATED by .local/guide_build/generate.py — do not edit by hand.
// Real flagged edits → guide examples. Peaks are the canonical int8 b64
// (10 bps) shape; audio is the same-origin clip under /guide-audio/.
import type { GuideExample } from '../types';

const data = {
    "failed_remerge_madd": {
        "id": "failed_remerge_madd",
        "title": "Verse cut short",
        "description": "A clean recitation the model wrongly broke at the closing madd — recovered by re-merging.",
        "render": "history_op",
        "chapter": 102,
        "clip_base_ms": 34957,
        "operations": [
            {
                "op_id": "055bcc2b-2e9d-4492-836b-06de5062d980",
                "op_type": "merge_segments",
                "merge_direction": "prev",
                "targets_before": [
                    {
                        "segment_uid": "68d885f3-104c-5da4-a973-ca73e3f638dd",
                        "time_start": 35207,
                        "time_end": 41675,
                        "matched_ref": "102:8:1-102:8:5",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_remerge_madd.mp3"
                    },
                    {
                        "segment_uid": "edb22d3c-02ff-5858-bfb4-7bc40feb63de",
                        "time_start": 41715,
                        "time_end": 43679,
                        "matched_ref": "",
                        "confidence": 0,
                        "audio_url": "/guide-audio/failed_remerge_madd.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "68d885f3-104c-5da4-a973-ca73e3f638dd",
                        "time_start": 35207,
                        "time_end": 43679,
                        "matched_ref": "102:8:1-102:8:5",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_remerge_madd.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "055bcc2b-2e9d-4492-836b-06de5062d980",
                "url": "/guide-audio/failed_remerge_madd.mp3",
                "start_ms": 34957,
                "end_ms": 43929,
                "bps": 10,
                "peaks_b64": "+Qb6BvsF+wXXNOQ33jbfNesp6CfeLt4x2zLhKslIuEu9PMFH5R7fKe4S7xHPLb06zzfZOuM15iviNuQr5DXeMd814SuxS7RHt0bGRdpA2i/BPtMz4S3PPcs70kHaNcBIqlGlUb9SyUrOPdwz2z/bL9Mw1jPXK90n2Sy1QalD1DreOto12TPYNto12jXbNNwy3TDaM9o02TbZNds21zTbNNox2jTlLugt7Rv3CPoI+wf7BQ=="
            }
        ]
    },
    "failed_remerge_start": {
        "id": "failed_remerge_start",
        "title": "Stray fragment at the start",
        "description": "The model split a tiny failed fragment off the front of a sound segment — merged back.",
        "render": "history_op",
        "chapter": 7,
        "clip_base_ms": 1196715,
        "operations": [
            {
                "op_id": "e90ba024-294a-4153-b4b3-38fff9377886",
                "op_type": "merge_segments",
                "targets_before": [
                    {
                        "segment_uid": "b4b07b66-4a3e-5968-bdeb-f4847e6c021c",
                        "time_start": 1196965,
                        "time_end": 1197517,
                        "matched_ref": "",
                        "confidence": 0,
                        "audio_url": "/guide-audio/failed_remerge_start.mp3"
                    },
                    {
                        "segment_uid": "90cd8110-9f0a-5cd5-91f0-afc5f5bac025",
                        "time_start": 1197548,
                        "time_end": 1208696,
                        "matched_ref": "7:88:1-7:88:17",
                        "confidence": 0.97,
                        "audio_url": "/guide-audio/failed_remerge_start.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "b4b07b66-4a3e-5968-bdeb-f4847e6c021c",
                        "time_start": 1196965,
                        "time_end": 1208696,
                        "matched_ref": "7:88:1-7:88:17",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_remerge_start.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "e90ba024-294a-4153-b4b3-38fff9377886",
                "url": "/guide-audio/failed_remerge_start.mp3",
                "start_ms": 1196715,
                "end_ms": 1208946,
                "bps": 10,
                "peaks_b64": "/AT7A/0E3xvaHuAa/Qb8BN0Z4RbmEuEZ4hbiEeAW5Q/nEOQQ5Q7jEPgM5BTnD/gI5RHkD+YM4g7nDecO5xHnEOAT3RLiEecR5hDhFuEW4RTmFeAS2hvjEecR6hHgFeAS3RPdFtoU5hThFeIV5w/eEuAS4RPgEuEa4hHkEuEV5hPgFOIT4BjlEOEV4xPhFuAR5BLmD+EN6Q7oDOsN5g7hGuoN4BHpDOIO4RffHN4b3hviF+MW4BbhE+Ef2hvhFd0Y4RbgFd0Z6RHtDesP6w7rEOAV5hHmEOYQ5RDiD+cS3hjqDuAT3RTdG90V9gr3B/sI4xfdHQ=="
            }
        ]
    },
    "reps_split_distinct": {
        "id": "reps_split_distinct",
        "title": "Two passes, one segment",
        "description": "The verse was recited twice with no gap; split into the two passes so each holds its own words.",
        "render": "edit_chain",
        "chapter": 5,
        "clip_base_ms": 975430,
        "operations": [
            {
                "op_id": "a2b1009e-536d-4d4a-8515-cd7e40f3759f",
                "op_type": "split_segment",
                "targets_before": [
                    {
                        "segment_uid": "81ec8415-a9e2-510a-bb79-719984a8d0f9",
                        "time_start": 975680,
                        "time_end": 991064,
                        "matched_ref": "5:45:1-5:45:16",
                        "confidence": 0.94,
                        "audio_url": "/guide-audio/reps_split_distinct.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "81ec8415-a9e2-510a-bb79-719984a8d0f9",
                        "time_start": 975680,
                        "time_end": 985181,
                        "matched_ref": "5:45:1-5:45:16",
                        "confidence": 0.94,
                        "audio_url": "/guide-audio/reps_split_distinct.mp3"
                    },
                    {
                        "segment_uid": "9cdc32c3-0f41-47f8-a372-d5cbb354d3db",
                        "time_start": 985181,
                        "time_end": 991064,
                        "matched_ref": "5:45:1-5:45:16",
                        "confidence": 0.94,
                        "audio_url": "/guide-audio/reps_split_distinct.mp3"
                    }
                ]
            },
            {
                "op_id": "ca371bcc-d9d7-480d-a66f-f5ae8018de9e",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "81ec8415-a9e2-510a-bb79-719984a8d0f9",
                        "time_start": 975680,
                        "time_end": 985181,
                        "matched_ref": "5:45:1-5:45:16",
                        "confidence": 0.94,
                        "audio_url": "/guide-audio/reps_split_distinct.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "81ec8415-a9e2-510a-bb79-719984a8d0f9",
                        "time_start": 975680,
                        "time_end": 985181,
                        "matched_ref": "5:45:1-5:45:12",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_split_distinct.mp3"
                    }
                ]
            },
            {
                "op_id": "fe1e7afa-c909-464c-b700-564c86abaeed",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "9cdc32c3-0f41-47f8-a372-d5cbb354d3db",
                        "time_start": 985181,
                        "time_end": 991064,
                        "matched_ref": "5:45:1-5:45:16",
                        "confidence": 0.94,
                        "audio_url": "/guide-audio/reps_split_distinct.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "9cdc32c3-0f41-47f8-a372-d5cbb354d3db",
                        "time_start": 985181,
                        "time_end": 991064,
                        "matched_ref": "5:45:11-5:45:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_split_distinct.mp3"
                    }
                ]
            },
            {
                "op_id": "c86c3cef-044b-40d0-a6a9-ef332c93a348",
                "op_type": "ignore_issue",
                "targets_before": [
                    {
                        "segment_uid": "81ec8415-a9e2-510a-bb79-719984a8d0f9",
                        "time_start": 975680,
                        "time_end": 985181,
                        "matched_ref": "5:45:1-5:45:12",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_split_distinct.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "81ec8415-a9e2-510a-bb79-719984a8d0f9",
                        "time_start": 975680,
                        "time_end": 985181,
                        "matched_ref": "5:45:1-5:45:12",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_split_distinct.mp3"
                    }
                ]
            },
            {
                "op_id": "88f7dc64-6379-46e9-9e5e-83c64c95e138",
                "op_type": "ignore_issue",
                "targets_before": [
                    {
                        "segment_uid": "9cdc32c3-0f41-47f8-a372-d5cbb354d3db",
                        "time_start": 985181,
                        "time_end": 991064,
                        "matched_ref": "5:45:11-5:45:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_split_distinct.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "9cdc32c3-0f41-47f8-a372-d5cbb354d3db",
                        "time_start": 985181,
                        "time_end": 991064,
                        "matched_ref": "5:45:11-5:45:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_split_distinct.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "a2b1009e-536d-4d4a-8515-cd7e40f3759f",
                "url": "/guide-audio/reps_split_distinct.mp3",
                "start_ms": 975430,
                "end_ms": 991314,
                "bps": 10,
                "peaks_b64": "6xXxEvIM6yK1d6N4umWceY9/ln+if5R/nH+gf5F/jH+lY8JuulbKO7N/r32Rf6p/mX+Xf5B/pna6TrZKpWulYsRjxl/EWqV/oH/NL7B/sH+5f8pdyFfPVKN/10PMa7Nyqn+ve6xumn+sf7h0lHu/eblxpH+If5B/lX+Lf6x/hn/AYLd/t3/KZ8tbxlSGf5R+oX/ITrtyt3++dsNwxGmjd6F/o3/ESrw/xlfQTs5fpn+ke5R/xFjOX8payF23Zc5Y2iKnf6p/y1zRV8hetGqgf5d/oH+mf6hayFfHTr1lmn+df55/0ibDUMZ9z1fRVclOq3+Qf5F/4CCxf7N/zGPJZsddyF7AW5R/tX+sf9E9yVnOYcddyGzEf6V/xF/EU8hTo22rYKRhpl+dZppyuWHoG+oU7hLsFPIP9Ayjeg=="
            }
        ]
    },
    "xverse_multi": {
        "id": "xverse_multi",
        "title": "Four verses in one segment",
        "description": "A long run spanning 85:4–85:7, split verse by verse.",
        "render": "edit_chain",
        "chapter": 85,
        "clip_base_ms": 10782,
        "operations": [
            {
                "op_id": "fe67d506-8480-44d7-a5a6-b4beacfa986f",
                "op_type": "split_segment",
                "targets_before": [
                    {
                        "segment_uid": "3eccb84f-862b-5cc1-ae2f-d296172cc76c",
                        "time_start": 11032,
                        "time_end": 23023,
                        "matched_ref": "85:4:1-85:7:6",
                        "confidence": 0.99,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "3eccb84f-862b-5cc1-ae2f-d296172cc76c",
                        "time_start": 11032,
                        "time_end": 13679,
                        "matched_ref": "85:4:1-85:4:3",
                        "confidence": 0.99,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    },
                    {
                        "segment_uid": "c5e751d0-0e85-4f52-acdf-25efecc5c89a",
                        "time_start": 13679,
                        "time_end": 23023,
                        "matched_ref": "85:5:1-85:7:6",
                        "confidence": 0.99,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ]
            },
            {
                "op_id": "617a2448-4ce1-49fd-9d16-15752b2bed9b",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "3eccb84f-862b-5cc1-ae2f-d296172cc76c",
                        "time_start": 11032,
                        "time_end": 13679,
                        "matched_ref": "85:4:1-85:4:3",
                        "confidence": 0.99,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "3eccb84f-862b-5cc1-ae2f-d296172cc76c",
                        "time_start": 11032,
                        "time_end": 13679,
                        "matched_ref": "85:4:1-85:4:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ]
            },
            {
                "op_id": "25b40932-0f90-40a6-ba81-7fc0897fd73c",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "c5e751d0-0e85-4f52-acdf-25efecc5c89a",
                        "time_start": 13679,
                        "time_end": 23023,
                        "matched_ref": "85:5:1-85:7:6",
                        "confidence": 0.99,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "c5e751d0-0e85-4f52-acdf-25efecc5c89a",
                        "time_start": 13679,
                        "time_end": 23023,
                        "matched_ref": "85:5:1-85:7:6",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ]
            },
            {
                "op_id": "d4abbbf1-579b-456b-b208-f41b0c9ca2ec",
                "op_type": "split_segment",
                "targets_before": [
                    {
                        "segment_uid": "c5e751d0-0e85-4f52-acdf-25efecc5c89a",
                        "time_start": 13679,
                        "time_end": 23023,
                        "matched_ref": "85:5:1-85:7:6",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "c5e751d0-0e85-4f52-acdf-25efecc5c89a",
                        "time_start": 13679,
                        "time_end": 16358,
                        "matched_ref": "85:5:1-85:5:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    },
                    {
                        "segment_uid": "445123e3-8828-4a7d-9df7-5a28d4b56614",
                        "time_start": 16358,
                        "time_end": 23023,
                        "matched_ref": "85:6:1-85:7:6",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ]
            },
            {
                "op_id": "e800198d-8dfc-4fe7-a2f4-c663af5aa707",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "c5e751d0-0e85-4f52-acdf-25efecc5c89a",
                        "time_start": 13679,
                        "time_end": 16358,
                        "matched_ref": "85:5:1-85:5:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "c5e751d0-0e85-4f52-acdf-25efecc5c89a",
                        "time_start": 13679,
                        "time_end": 16358,
                        "matched_ref": "85:5:1-85:5:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ]
            },
            {
                "op_id": "cac07755-156b-440d-baf9-327dfbad92e1",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "445123e3-8828-4a7d-9df7-5a28d4b56614",
                        "time_start": 16358,
                        "time_end": 23023,
                        "matched_ref": "85:6:1-85:7:6",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "445123e3-8828-4a7d-9df7-5a28d4b56614",
                        "time_start": 16358,
                        "time_end": 23023,
                        "matched_ref": "85:6:1-85:7:6",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ]
            },
            {
                "op_id": "4f60c124-5937-4cff-b9ab-8ef1dcdb8742",
                "op_type": "split_segment",
                "targets_before": [
                    {
                        "segment_uid": "445123e3-8828-4a7d-9df7-5a28d4b56614",
                        "time_start": 16358,
                        "time_end": 23023,
                        "matched_ref": "85:6:1-85:7:6",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "445123e3-8828-4a7d-9df7-5a28d4b56614",
                        "time_start": 16358,
                        "time_end": 18716,
                        "matched_ref": "85:6:1-85:6:4",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    },
                    {
                        "segment_uid": "fdd2bb63-4e9c-4a76-9f88-761ae20d53d1",
                        "time_start": 18716,
                        "time_end": 23023,
                        "matched_ref": "85:7:1-85:7:6",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ]
            },
            {
                "op_id": "56983029-e1d2-47ce-a852-d6618878f88f",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "445123e3-8828-4a7d-9df7-5a28d4b56614",
                        "time_start": 16358,
                        "time_end": 18716,
                        "matched_ref": "85:6:1-85:6:4",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "445123e3-8828-4a7d-9df7-5a28d4b56614",
                        "time_start": 16358,
                        "time_end": 18716,
                        "matched_ref": "85:6:1-85:6:4",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ]
            },
            {
                "op_id": "44b9e56c-bfbf-479e-991a-4d2f691d12ca",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "fdd2bb63-4e9c-4a76-9f88-761ae20d53d1",
                        "time_start": 18716,
                        "time_end": 23023,
                        "matched_ref": "85:7:1-85:7:6",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "fdd2bb63-4e9c-4a76-9f88-761ae20d53d1",
                        "time_start": 18716,
                        "time_end": 23023,
                        "matched_ref": "85:7:1-85:7:6",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_multi.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "fe67d506-8480-44d7-a5a6-b4beacfa986f",
                "url": "/guide-audio/xverse_multi.mp3",
                "start_ms": 10782,
                "end_ms": 23273,
                "bps": 10,
                "peaks_b64": "9gz4CvgJ1C7JNcIwpkinS7pA0iDzD6o8rC62KtAj2yrUIr482iP1Es8zzynOKs4tsjWpQ6BO8g31CuQgrjLTH+Ic4hulOJ5Rm0vLL9QsuCu0KtwrzzLRJa41uTDMK80rySnHL6s/vjygTfUL9AzJMskv1x3MLc8itzWbPqxIsjzCNqM0nTekO8c4xTvEOMY9xzbKNa49n1ijVPQR9w3LOsI71yy5OK09rUqpTqZPrz6sKrMztjmsOdYlriyhL7sv1SXELKNBqELIJ9wk2CTHI+QaxiDFJsUtsSmuM6s7zi/KLtcp0SvOLc0qqj2kWrVK8gr1C9cqyCY="
            }
        ]
    },
    "xverse_waqf": {
        "id": "xverse_waqf",
        "title": "Waqf — split at the pause",
        "description": "The reciter paused between 56:39 and 56:40 but the model missed the silence; split at it.",
        "render": "edit_chain",
        "chapter": 56,
        "clip_base_ms": 164910,
        "operations": [
            {
                "op_id": "1938b54f-68a9-4dde-921d-b8c6911884c2",
                "op_type": "split_segment",
                "targets_before": [
                    {
                        "segment_uid": "019d5aab-1433-7d8b-bc67-a7d548e8a56b",
                        "time_start": 165160,
                        "time_end": 174380,
                        "matched_ref": "56:39:1-56:40:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_waqf.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "f98839df-c88c-4cfa-bca6-8bd510677d99",
                        "time_start": 165160,
                        "time_end": 169400,
                        "matched_ref": "56:39:1-56:40:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_waqf.mp3"
                    },
                    {
                        "segment_uid": "7a6a8b77-26b5-4b48-90d9-6de7123ca518",
                        "time_start": 169400,
                        "time_end": 174380,
                        "matched_ref": "56:39:1-56:40:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_waqf.mp3"
                    }
                ]
            },
            {
                "op_id": "0396f586-34b7-4760-8782-3ea535e7777a",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "f98839df-c88c-4cfa-bca6-8bd510677d99",
                        "time_start": 165160,
                        "time_end": 169400,
                        "matched_ref": "56:39:1-56:40:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_waqf.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "f98839df-c88c-4cfa-bca6-8bd510677d99",
                        "time_start": 165160,
                        "time_end": 169400,
                        "matched_ref": "56:39:1-56:39:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_waqf.mp3"
                    }
                ]
            },
            {
                "op_id": "1ad246c4-86e1-4ea9-a7c4-89c60e17d8f8",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "7a6a8b77-26b5-4b48-90d9-6de7123ca518",
                        "time_start": 169400,
                        "time_end": 174380,
                        "matched_ref": "56:39:1-56:40:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_waqf.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "7a6a8b77-26b5-4b48-90d9-6de7123ca518",
                        "time_start": 169400,
                        "time_end": 174380,
                        "matched_ref": "56:40:1-56:40:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_waqf.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "1938b54f-68a9-4dde-921d-b8c6911884c2",
                "url": "/guide-audio/xverse_waqf.mp3",
                "start_ms": 164910,
                "end_ms": 174630,
                "bps": 10,
                "peaks_b64": "6hnyDfcJ1iXKLMAztzW7P8YuvDa8KMAoxynBJ8ErxSe7Mrwvui7AMccsvT3DL7oztEuyPb45s0K2OLs4tDe3MLgyvyy/MsE0ujanQLkxtzWwO7UxtizpEfQMu0u1TrkwuTCsQKA+qkC+L7YrvCy+J78lvCm9Jr8ntyq5KbkqtDqsO7Q4vC7GK7tQqTyzOOMTyDDCN8wvyCrGMsYvxDDCLMQxxijELMUvvTK/LLQ8uT26NrM2szetNLI15xLyD/YNzEA="
            }
        ]
    },
    "reps_lookback": {
        "id": "reps_lookback",
        "title": "Reciter looked back",
        "description": "The reciter went back to re-recite earlier words; split so each pass maps to what was said.",
        "render": "edit_chain",
        "chapter": 7,
        "clip_base_ms": 1094260,
        "operations": [
            {
                "op_id": "786ff31d-4e7a-46be-a9e7-5743da2d4130",
                "op_type": "split_segment",
                "targets_before": [
                    {
                        "segment_uid": "ca8ff7d1-5215-5e7c-bd92-4de75f7da1b8",
                        "time_start": 1094510,
                        "time_end": 1113305,
                        "matched_ref": "7:50:6-7:50:10",
                        "confidence": 0.92,
                        "audio_url": "/guide-audio/reps_lookback.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "ca8ff7d1-5215-5e7c-bd92-4de75f7da1b8",
                        "time_start": 1094510,
                        "time_end": 1102100,
                        "matched_ref": "7:50:6-7:50:10",
                        "confidence": 0.92,
                        "audio_url": "/guide-audio/reps_lookback.mp3"
                    },
                    {
                        "segment_uid": "9f548a8c-dbe9-486d-81ee-3e39ca9ca5cd",
                        "time_start": 1102100,
                        "time_end": 1113305,
                        "matched_ref": "7:50:6-7:50:10",
                        "confidence": 0.92,
                        "audio_url": "/guide-audio/reps_lookback.mp3"
                    }
                ]
            },
            {
                "op_id": "2852ecc5-fb2b-411c-87ef-06cc92fe80c7",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "ca8ff7d1-5215-5e7c-bd92-4de75f7da1b8",
                        "time_start": 1094510,
                        "time_end": 1102100,
                        "matched_ref": "7:50:6-7:50:10",
                        "confidence": 0.92,
                        "audio_url": "/guide-audio/reps_lookback.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "ca8ff7d1-5215-5e7c-bd92-4de75f7da1b8",
                        "time_start": 1094510,
                        "time_end": 1102100,
                        "matched_ref": "7:50:6-7:50:10",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_lookback.mp3"
                    }
                ]
            },
            {
                "op_id": "aa4d593c-1662-4a88-9929-24b813746467",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "9f548a8c-dbe9-486d-81ee-3e39ca9ca5cd",
                        "time_start": 1102100,
                        "time_end": 1113305,
                        "matched_ref": "7:50:6-7:50:10",
                        "confidence": 0.92,
                        "audio_url": "/guide-audio/reps_lookback.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "9f548a8c-dbe9-486d-81ee-3e39ca9ca5cd",
                        "time_start": 1102100,
                        "time_end": 1113305,
                        "matched_ref": "7:50:1-7:50:10",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_lookback.mp3"
                    }
                ]
            },
            {
                "op_id": "9197ae3a-a651-48df-9e6a-07c3fa56ed88",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "9f548a8c-dbe9-486d-81ee-3e39ca9ca5cd",
                        "time_start": 1102100,
                        "time_end": 1113305,
                        "matched_ref": "7:50:1-7:50:10",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_lookback.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "9f548a8c-dbe9-486d-81ee-3e39ca9ca5cd",
                        "time_start": 1102100,
                        "time_end": 1113305,
                        "matched_ref": "7:50:1-7:50:7",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_lookback.mp3"
                    }
                ]
            },
            {
                "op_id": "575a1386-cbcb-48d1-89b8-7bc26eb2bce7",
                "op_type": "ignore_issue",
                "targets_before": [
                    {
                        "segment_uid": "ca8ff7d1-5215-5e7c-bd92-4de75f7da1b8",
                        "time_start": 1094510,
                        "time_end": 1102100,
                        "matched_ref": "7:50:6-7:50:10",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_lookback.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "ca8ff7d1-5215-5e7c-bd92-4de75f7da1b8",
                        "time_start": 1094510,
                        "time_end": 1102100,
                        "matched_ref": "7:50:6-7:50:10",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_lookback.mp3"
                    }
                ]
            },
            {
                "op_id": "99ee8752-cb5b-4aae-9507-6db595bdc2af",
                "op_type": "ignore_issue",
                "targets_before": [
                    {
                        "segment_uid": "9f548a8c-dbe9-486d-81ee-3e39ca9ca5cd",
                        "time_start": 1102100,
                        "time_end": 1113305,
                        "matched_ref": "7:50:1-7:50:7",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_lookback.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "9f548a8c-dbe9-486d-81ee-3e39ca9ca5cd",
                        "time_start": 1102100,
                        "time_end": 1113305,
                        "matched_ref": "7:50:1-7:50:7",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_lookback.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "786ff31d-4e7a-46be-a9e7-5743da2d4130",
                "url": "/guide-audio/reps_lookback.mp3",
                "start_ms": 1094260,
                "end_ms": 1113555,
                "bps": 10,
                "peaks_b64": "6B/jH94ngX+BVKxHmjeBXZJCq1OgRaNRmUKxPp5VgVuBdYJ4g2SJVZ9Mn0a0OKpIk0uXaYF/gX+RWIFbgVynQ5FNgVSLZa1YrVuBQYFtkmOTVZVbjWeBf5JnrUqfWqxHlFekPKZdg3+KeZFykWuNf5V0gVWBeZFegX+HdYRogX2OWoFmk1mBbotygVOGbYpfgXyBfIFtoTfiItYy1SejVod3pkGWVZlskHSXaJlkm1SmToJ8mVyBcJVglVieZZNml0aWXpNmkmeQZ4VrhFyBa4FhgWCOX4dkgWWBdoFzgWGBc4FwgVuEY4VrimmlUJRVnFSMcoF3h22uZ7Q87xDsDppUk1WPQYJZszSsSq9Hn02UV6BNlkymSpJHg2OGTIFkgXSPRaI+jXzWOfESnXaBcIFch1qBcYJdn0+Bda5DqjjKNYRFk0O2QrI/qEqxQIFRkkm1Q6hRoUmBe606t0eBQoFmhjmhVJlfk1ChT5dSgVOcUoFogW6BU9Ut2yDdJeYe"
            }
        ]
    },
    "reps_multiple": {
        "id": "reps_multiple",
        "title": "Several repeats",
        "description": "Multiple repeated passes resolved by splitting them apart.",
        "render": "edit_chain",
        "chapter": 11,
        "clip_base_ms": 1518855,
        "operations": [
            {
                "op_id": "c2f07845-fee8-44b7-a9cb-1df430a2a47c",
                "op_type": "split_segment",
                "targets_before": [
                    {
                        "segment_uid": "081447d6-ef8a-5841-8073-c0ace4d619e5",
                        "time_start": 1519105,
                        "time_end": 1544675,
                        "matched_ref": "11:76:10-11:77:9",
                        "confidence": 0.93,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "081447d6-ef8a-5841-8073-c0ace4d619e5",
                        "time_start": 1519105,
                        "time_end": 1526875,
                        "matched_ref": "11:76:10-11:76:14",
                        "confidence": 0.93,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    },
                    {
                        "segment_uid": "6a3c8446-ac33-41d4-9479-bed0453a6b2f",
                        "time_start": 1526875,
                        "time_end": 1544675,
                        "matched_ref": "11:77:1-11:77:9",
                        "confidence": 0.93,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ]
            },
            {
                "op_id": "494508c3-a55d-473d-ab62-ac5fa7444579",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "081447d6-ef8a-5841-8073-c0ace4d619e5",
                        "time_start": 1519105,
                        "time_end": 1526875,
                        "matched_ref": "11:76:10-11:76:14",
                        "confidence": 0.93,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "081447d6-ef8a-5841-8073-c0ace4d619e5",
                        "time_start": 1519105,
                        "time_end": 1526875,
                        "matched_ref": "11:76:10-11:76:14",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ]
            },
            {
                "op_id": "2f260feb-540c-421e-b5fb-e744804206d3",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "6a3c8446-ac33-41d4-9479-bed0453a6b2f",
                        "time_start": 1526875,
                        "time_end": 1544675,
                        "matched_ref": "11:77:1-11:77:9",
                        "confidence": 0.93,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "6a3c8446-ac33-41d4-9479-bed0453a6b2f",
                        "time_start": 1526875,
                        "time_end": 1544675,
                        "matched_ref": "11:77:1-11:77:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ]
            },
            {
                "op_id": "91557dc9-072b-4d20-81d6-a0ff61330f33",
                "op_type": "split_segment",
                "targets_before": [
                    {
                        "segment_uid": "6a3c8446-ac33-41d4-9479-bed0453a6b2f",
                        "time_start": 1526875,
                        "time_end": 1544675,
                        "matched_ref": "11:77:1-11:77:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "6a3c8446-ac33-41d4-9479-bed0453a6b2f",
                        "time_start": 1526875,
                        "time_end": 1534093,
                        "matched_ref": "11:77:1-11:77:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    },
                    {
                        "segment_uid": "291e0e75-b61e-4b24-83e2-c7b4247c8e41",
                        "time_start": 1534093,
                        "time_end": 1544675,
                        "matched_ref": "11:77:1-11:77:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ]
            },
            {
                "op_id": "bacbc221-23d6-42ac-a6d0-6eead957a063",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "6a3c8446-ac33-41d4-9479-bed0453a6b2f",
                        "time_start": 1526875,
                        "time_end": 1534093,
                        "matched_ref": "11:77:1-11:77:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "6a3c8446-ac33-41d4-9479-bed0453a6b2f",
                        "time_start": 1526875,
                        "time_end": 1534093,
                        "matched_ref": "11:76:10-11:76:14",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ]
            },
            {
                "op_id": "b94afc6d-5611-46a6-ba74-fa0ef3896a31",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "291e0e75-b61e-4b24-83e2-c7b4247c8e41",
                        "time_start": 1534093,
                        "time_end": 1544675,
                        "matched_ref": "11:77:1-11:77:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "291e0e75-b61e-4b24-83e2-c7b4247c8e41",
                        "time_start": 1534093,
                        "time_end": 1544675,
                        "matched_ref": "11:77:1-11:77:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ]
            },
            {
                "op_id": "46f953f3-07ea-46b3-a331-a8f67b37c074",
                "op_type": "ignore_issue",
                "targets_before": [
                    {
                        "segment_uid": "081447d6-ef8a-5841-8073-c0ace4d619e5",
                        "time_start": 1519105,
                        "time_end": 1526875,
                        "matched_ref": "11:76:10-11:76:14",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "081447d6-ef8a-5841-8073-c0ace4d619e5",
                        "time_start": 1519105,
                        "time_end": 1526875,
                        "matched_ref": "11:76:10-11:76:14",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ]
            },
            {
                "op_id": "ca1cc4b7-36d8-4638-8355-2655ac761961",
                "op_type": "ignore_issue",
                "targets_before": [
                    {
                        "segment_uid": "081447d6-ef8a-5841-8073-c0ace4d619e5",
                        "time_start": 1519105,
                        "time_end": 1526875,
                        "matched_ref": "11:76:10-11:76:14",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "081447d6-ef8a-5841-8073-c0ace4d619e5",
                        "time_start": 1519105,
                        "time_end": 1526875,
                        "matched_ref": "11:76:10-11:76:14",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ]
            },
            {
                "op_id": "6e3882eb-da44-42c8-902c-b009f64d2098",
                "op_type": "ignore_issue",
                "targets_before": [
                    {
                        "segment_uid": "6a3c8446-ac33-41d4-9479-bed0453a6b2f",
                        "time_start": 1526875,
                        "time_end": 1534093,
                        "matched_ref": "11:76:10-11:76:14",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "6a3c8446-ac33-41d4-9479-bed0453a6b2f",
                        "time_start": 1526875,
                        "time_end": 1534093,
                        "matched_ref": "11:76:10-11:76:14",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ]
            },
            {
                "op_id": "5169b2fe-4f66-4dba-8311-58a8e20af9f6",
                "op_type": "ignore_issue",
                "targets_before": [
                    {
                        "segment_uid": "291e0e75-b61e-4b24-83e2-c7b4247c8e41",
                        "time_start": 1534093,
                        "time_end": 1544675,
                        "matched_ref": "11:77:1-11:77:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "291e0e75-b61e-4b24-83e2-c7b4247c8e41",
                        "time_start": 1534093,
                        "time_end": 1544675,
                        "matched_ref": "11:77:1-11:77:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/reps_multiple.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "c2f07845-fee8-44b7-a9cb-1df430a2a47c",
                "url": "/guide-audio/reps_multiple.mp3",
                "start_ms": 1518855,
                "end_ms": 1544925,
                "bps": 10,
                "peaks_b64": "7BTkGeAmsX/ANMVAzDTMOrtBs0G+QrRFmFizQL1JsTO+PbhBrlCGZpxm0zbMQblJoFO3U6Zesz+rTYZ+kn+jWIxZgXGBboFqh3KXVaJLslCkVKVQj3WMWrlEsWG3T7dIgXCDedM26xXCNb06uUjDPcFJvEzAQcJBt0bIRcFHy0K+T8JNwEzHS79GxVO8S8RKu0OyTLlPtl+wU4F/vi3nJNwa5SCDf8E0r1WcUZRLlV6jT6FJtkSpR4N4p0y4WrJFyDu5V61tnGCVYOoUtVm7SbxPpVKxT7hRo2PJPYF/hX+ba5xBnEmWUpJprD2qSbhRtVqoa4F/rESmRLpJpGSmf6t/3zfjHrs3wDqxU7VVwEa/QqVKrUW5ULhDplCtS55OlUyQTIRPi2+Bf9Y05h/hG4V/jGeBbLRHrT2wPLFCtkG1QL09g2OSYKRGwEicTZFAn22BfopZgk2BX4Rpi2KHfolooUmsS6dHm1GoXJx4r1aqf6Fb2SvHSLFTtD25Q6RJpFGRXa1QsFCgS5F5m2CWYZV74yeOf7NApE2zSp5dqVGzUJRZpE6iVqtPr0e+Rb5Jv0ezVaRdn1+tY6pmsWi4XrxfuWK+W8JNvTjMR8hWwlrDXrRGuWK0Xtg+o3+ra7J22Tmsf8w4x1TIU5p2u0XERqBxr3/ZPLdTnH+QeqRvoma/T+Ub6BjuIA=="
            }
        ]
    },
    "xverse_wasl": {
        "id": "xverse_wasl",
        "title": "Wasl — split and annotate",
        "description": "The reciter joined 1:6 into 1:7 with no pause; split where they separate best and tag the boundary wasl.",
        "render": "edit_chain",
        "chapter": 1,
        "clip_base_ms": 29235,
        "operations": [
            {
                "op_id": "7a13a797-f120-41a6-895a-662de72b24e8",
                "op_type": "split_segment",
                "targets_before": [
                    {
                        "segment_uid": "2108f8cf-7893-5a9b-83b5-a70e4b6eddd8",
                        "time_start": 29485,
                        "time_end": 36255,
                        "matched_ref": "1:6:1-1:7:4",
                        "confidence": 0.98,
                        "audio_url": "/guide-audio/xverse_wasl.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "2108f8cf-7893-5a9b-83b5-a70e4b6eddd8",
                        "time_start": 29485,
                        "time_end": 32175,
                        "matched_ref": "1:6:1-1:6:3",
                        "confidence": 0.98,
                        "audio_url": "/guide-audio/xverse_wasl.mp3",
                        "is_wasl": true
                    },
                    {
                        "segment_uid": "8a92c641-25ed-469c-8710-ea59e0da2a81",
                        "time_start": 32175,
                        "time_end": 36255,
                        "matched_ref": "1:7:1-1:7:4",
                        "confidence": 0.98,
                        "audio_url": "/guide-audio/xverse_wasl.mp3"
                    }
                ]
            },
            {
                "op_id": "396b7a1d-ef75-411f-aa0b-ac2b1457966f",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "2108f8cf-7893-5a9b-83b5-a70e4b6eddd8",
                        "time_start": 29485,
                        "time_end": 32175,
                        "matched_ref": "1:6:1-1:6:3",
                        "confidence": 0.98,
                        "audio_url": "/guide-audio/xverse_wasl.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "2108f8cf-7893-5a9b-83b5-a70e4b6eddd8",
                        "time_start": 29485,
                        "time_end": 32175,
                        "matched_ref": "1:6:1-1:6:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_wasl.mp3"
                    }
                ]
            },
            {
                "op_id": "e93bf6a2-30d7-4d95-bbc4-3d0760115610",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "8a92c641-25ed-469c-8710-ea59e0da2a81",
                        "time_start": 32175,
                        "time_end": 36255,
                        "matched_ref": "1:7:1-1:7:4",
                        "confidence": 0.98,
                        "audio_url": "/guide-audio/xverse_wasl.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "8a92c641-25ed-469c-8710-ea59e0da2a81",
                        "time_start": 32175,
                        "time_end": 36255,
                        "matched_ref": "1:7:1-1:7:4",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_wasl.mp3"
                    }
                ]
            },
            {
                "op_id": "23323661-60d1-4b9b-920f-50e89a748cde",
                "op_type": "trim_segment",
                "targets_before": [
                    {
                        "segment_uid": "2108f8cf-7893-5a9b-83b5-a70e4b6eddd8",
                        "time_start": 29485,
                        "time_end": 32175,
                        "matched_ref": "1:6:1-1:6:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_wasl.mp3",
                        "is_wasl": true
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "2108f8cf-7893-5a9b-83b5-a70e4b6eddd8",
                        "time_start": 29485,
                        "time_end": 32075,
                        "matched_ref": "1:6:1-1:6:3",
                        "confidence": 1,
                        "audio_url": "/guide-audio/xverse_wasl.mp3",
                        "is_wasl": true
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "7a13a797-f120-41a6-895a-662de72b24e8",
                "url": "/guide-audio/xverse_wasl.mp3",
                "start_ms": 29235,
                "end_ms": 36505,
                "bps": 10,
                "peaks_b64": "+Qf6B/cK+QfKRsZJ4yetVqhmqW30FqlDmFKGfoxmn1eoY6J6sUa5QadF2D62PaFKzSyhVKNjolKXULU+tjqvcqxvqmeyTLdRwjzGP8lAzkKzVLRXsEezPMI1rUOxTY1tnWW+P8JAvVeldqB2r1meS7JVr1iuV8VIo1a5SLVVwUbvEPEP9QzxDPcL+Aj0C/MZ"
            }
        ]
    },
    "qalqala_extend": {
        "id": "qalqala_extend",
        "title": "Clipped qalqala",
        "description": "A slow qalqala on the closing letter ran past the boundary; extend so the bounce isn't cut.",
        "render": "history_op",
        "chapter": 45,
        "clip_base_ms": 446020,
        "operations": [
            {
                "op_id": "7101de31-38b7-4802-8720-e5aeadf9e04a",
                "op_type": "trim_segment",
                "targets_before": [
                    {
                        "segment_uid": "019d5c88-f506-72c7-b544-53e443e780f0",
                        "time_start": 446270,
                        "time_end": 452030,
                        "matched_ref": "45:29:1-45:29:5",
                        "confidence": 0.97,
                        "audio_url": "/guide-audio/qalqala_extend.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "019d5c88-f506-72c7-b544-53e443e780f0",
                        "time_start": 446270,
                        "time_end": 452670,
                        "matched_ref": "45:29:1-45:29:5",
                        "confidence": 1,
                        "audio_url": "/guide-audio/qalqala_extend.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "7101de31-38b7-4802-8720-e5aeadf9e04a",
                "url": "/guide-audio/qalqala_extend.mp3",
                "start_ms": 446020,
                "end_ms": 452920,
                "bps": 10,
                "peaks_b64": "/wEAAAAAAACmSqJMpkWlTKtBqESnP70p3hzWIs4mxiq2N7Q73RjZGc8iyDPFL8oswDLHH9Ya4BPmEOQS5RHxDtQc0R7fFdYexyusO7g7vTncG+sT4hfgGt8T3xbeEuMQ5hHnEuoR4xrVIeYV6hX4CLU4sDH6BvwE/AP9AvYM9Q3+Av8B/wH/Af8B"
            }
        ]
    },
    "missing_autofill": {
        "id": "missing_autofill",
        "title": "One word missing",
        "description": "Audio is present but the last word wasn't assigned — auto-fill places it.",
        "render": "history_op",
        "chapter": 42,
        "clip_base_ms": 221425,
        "operations": [
            {
                "op_id": "fd559c38-8185-4b57-b1b8-ad84ca77bf87",
                "op_type": "auto_fix_missing_word",
                "targets_before": [
                    {
                        "segment_uid": "e482a62e-fa1c-519d-a1a8-6ad3561cd9b7",
                        "time_start": 221675,
                        "time_end": 225685,
                        "matched_ref": "42:11:14-42:11:15",
                        "confidence": 1,
                        "audio_url": "/guide-audio/missing_autofill.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "e482a62e-fa1c-519d-a1a8-6ad3561cd9b7",
                        "time_start": 221675,
                        "time_end": 225685,
                        "matched_ref": "42:11:14-42:11:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/missing_autofill.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "fd559c38-8185-4b57-b1b8-ad84ca77bf87",
                "url": "/guide-audio/missing_autofill.mp3",
                "start_ms": 221425,
                "end_ms": 225935,
                "bps": 10,
                "peaks_b64": "/wH/Af8B/wHTI9Ql5hfqFvcHyCTHJvMQzinSIuQZ5xjpFPMJ3B3gG9Yi4hrgH9Yq1yjTLN4f9QfTIs4l3BviFukU6BToE+oT8gz8A/4C/gL/Af8C/wH/Af8B"
            }
        ]
    },
    "missing_fill_start": {
        "id": "missing_fill_start",
        "title": "Missing word at the start",
        "description": "The opening word of the segment was unassigned — extending the reference recovers it.",
        "render": "history_op",
        "chapter": 18,
        "clip_base_ms": 215035,
        "operations": [
            {
                "op_id": "6569e0e3-8e94-4679-999e-10d1e8e4adb7",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "f71daaa5-705f-55e0-b04b-d5d786a25ac1",
                        "time_start": 215285,
                        "time_end": 223780,
                        "matched_ref": "18:16:8-18:16:14",
                        "confidence": 0.92,
                        "audio_url": "/guide-audio/missing_fill_start.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "f71daaa5-705f-55e0-b04b-d5d786a25ac1",
                        "time_start": 215285,
                        "time_end": 223780,
                        "matched_ref": "18:16:7-18:16:14",
                        "confidence": 1,
                        "audio_url": "/guide-audio/missing_fill_start.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "6569e0e3-8e94-4679-999e-10d1e8e4adb7",
                "url": "/guide-audio/missing_fill_start.mp3",
                "start_ms": 215035,
                "end_ms": 224030,
                "bps": 10,
                "peaks_b64": "8RDuEO8R4Ra2RMoz4B7ZIdck1SPdJNsj1STZId4o1CrVJtUe0ivMKdgj3CLaH94d4yjaJ+Ac4hnNPNkn3hnrGM8tzSjjHe0Q4BrSHtEv3CHcINkk1SbVJuUU0SHOLdwl3SPdIusW0ifhGtEf1DvLOOEe6hjPMNUo4xbmFNcl2iTbHNce3xjgFeEX4RvoGukR1CbQLvEP4BLpIeQZ8w/YHOMe2x/1DPcI9wv3C/kJ+AnjHw=="
            }
        ]
    },
    "basmala_nonfatiha": {
        "id": "basmala_nonfatiha",
        "title": "Basmala before a non-Fatiha surah",
        "description": "The opening basmala/istiʿādha isn't part of the surah's verses — deleted.",
        "render": "history_op",
        "chapter": 2,
        "clip_base_ms": 5800,
        "operations": [
            {
                "op_id": "628b0bc3-9c46-454a-8fa3-c6742c15f020",
                "op_type": "delete_segment",
                "targets_before": [
                    {
                        "segment_uid": "5217834e-9a61-5c13-b8d6-31927c0dab1b",
                        "time_start": 6050,
                        "time_end": 14300,
                        "matched_ref": "",
                        "confidence": 0,
                        "audio_url": "/guide-audio/basmala_nonfatiha.mp3"
                    }
                ],
                "targets_after": []
            }
        ],
        "peaks": [
            {
                "op_id": "628b0bc3-9c46-454a-8fa3-c6742c15f020",
                "url": "/guide-audio/basmala_nonfatiha.mp3",
                "start_ms": 5800,
                "end_ms": 14550,
                "bps": 10,
                "peaks_b64": "AAAAAAAA/wGrNaBAsUC+N7g8xjLBNcskziunTqZLvybHKdEtwjDJJNUm1R+7KLY3ySbeHZ1MlkO4PcIzuES8LaQ+rT3IM8I2zCXJLcQ2yyzRM9ks9QzxDu4P1iXlGuUZxjPGNNsmziyyQKlBsTLZKcsszB65NMIs8w3dKr8tvy6sMckkwS3JJcMlpTStMc0myT/SQMNCxUa/Q8BG2zPvEPQT8Q/6BfUJ+gj7BvsH"
            }
        ]
    },
    "failed_nonquran_takbir": {
        "id": "failed_nonquran_takbir",
        "title": "Takbīr between surahs",
        "description": "Non-Quranic audio (a takbīr) — deleted so it never reaches the timestamps.",
        "render": "history_op",
        "chapter": 30,
        "clip_base_ms": 1251810,
        "operations": [
            {
                "op_id": "f092422c-17f7-4161-a3f7-99d35e7117e7",
                "op_type": "delete_segment",
                "targets_before": [
                    {
                        "segment_uid": "1b39efe7-6889-55a1-9d59-1a5553e57a2d",
                        "time_start": 1252060,
                        "time_end": 1253050,
                        "matched_ref": "",
                        "confidence": 0,
                        "audio_url": "/guide-audio/failed_nonquran_takbir.mp3"
                    }
                ],
                "targets_after": []
            }
        ],
        "peaks": [
            {
                "op_id": "f092422c-17f7-4161-a3f7-99d35e7117e7",
                "url": "/guide-audio/failed_nonquran_takbir.mp3",
                "start_ms": 1251810,
                "end_ms": 1253300,
                "bps": 10,
                "peaks_b64": "+Aj5B9carVKzTLpTuE3SMdQn3hzhFugh7RLmGA=="
            }
        ]
    },
    "failed_nonquran_speech": {
        "id": "failed_nonquran_speech",
        "title": "Spoken aside",
        "description": "Non-Quranic speech captured by the recording — deleted.",
        "render": "history_op",
        "chapter": 2,
        "clip_base_ms": 4282,
        "operations": [
            {
                "op_id": "48605f4b-dc34-4e80-8ce3-9e546488ccf0",
                "op_type": "delete_segment",
                "targets_before": [
                    {
                        "segment_uid": "73a79425-2d93-5163-a22f-0f72f430d193",
                        "time_start": 4532,
                        "time_end": 5720,
                        "matched_ref": "",
                        "confidence": 0,
                        "audio_url": "/guide-audio/failed_nonquran_speech.mp3"
                    }
                ],
                "targets_after": []
            }
        ],
        "peaks": [
            {
                "op_id": "48605f4b-dc34-4e80-8ce3-9e546488ccf0",
                "url": "/guide-audio/failed_nonquran_speech.mp3",
                "start_ms": 4282,
                "end_ms": 5970,
                "bps": 10,
                "peaks_b64": "/gL/Af8B1zvrG9lc8A/kIfcH+Qb9AwAAAAAAAAAAAAA="
            }
        ]
    },
    "failed_nonquran_speech2": {
        "id": "failed_nonquran_speech2",
        "title": "Spoken aside (2)",
        "description": "Another non-Quranic interjection — deleted.",
        "render": "history_op",
        "chapter": 2,
        "clip_base_ms": 2320,
        "operations": [
            {
                "op_id": "9ae795ba-9816-425a-bbd3-ac0a2fa1a0b0",
                "op_type": "delete_segment",
                "targets_before": [
                    {
                        "segment_uid": "87f17e95-5b04-50cf-a405-37bfbef4d028",
                        "time_start": 2570,
                        "time_end": 4492,
                        "matched_ref": "",
                        "confidence": 0,
                        "audio_url": "/guide-audio/failed_nonquran_speech2.mp3"
                    }
                ],
                "targets_after": []
            }
        ],
        "peaks": [
            {
                "op_id": "9ae795ba-9816-425a-bbd3-ac0a2fa1a0b0",
                "url": "/guide-audio/failed_nonquran_speech2.mp3",
                "start_ms": 2320,
                "end_ms": 4742,
                "bps": 10,
                "peaks_b64": "8hDvEfEUy0bTOMlHz0XmEt1Z5xfsHu0Z7hbnIuE62DnqJP0E/gH+Af8C/wH+AdY6"
            }
        ]
    },
    "failed_intentional_dup": {
        "id": "failed_intentional_dup",
        "title": "Defective duplicate",
        "description": "The reciter repeated 14:46 with an audio defect; the clean take already exists, so this one is marked failed to drop it.",
        "render": "history_op",
        "chapter": 14,
        "clip_base_ms": 1012823,
        "operations": [
            {
                "op_id": "4aabeb21-3873-40cd-b15f-85177994293f",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "27ff2212-dd74-5858-9cb1-671824189394",
                        "time_start": 1028479,
                        "time_end": 1033524,
                        "matched_ref": "14:46:9-14:46:12",
                        "confidence": 0.78,
                        "audio_url": "/guide-audio/failed_intentional_dup.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "27ff2212-dd74-5858-9cb1-671824189394",
                        "time_start": 1028479,
                        "time_end": 1033524,
                        "matched_ref": "",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_dup.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "4aabeb21-3873-40cd-b15f-85177994293f",
                "url": "/guide-audio/failed_intentional_dup.mp3",
                "start_ms": 1012823,
                "end_ms": 1033774,
                "bps": 10,
                "peaks_b64": "8xD1DPMNszquP5lZj3KYZIN0sEewS7hGsjKmTsE7yTLML8E7zTC7Ocoy8hPcI7Y4sE21TckmuzbbK9QmvV2zZ7lcwzbEP8E4xzm+R803zTrKMsgtzjDOMsUxxjS3QbNGp0S2Pc4tk23HONUnziKwQpNplnKpcdYo2STYIMos1yLzD+MbzynKNMsz0B/PGtIi1yXEKqhMvS7ALsQwwS3AL780wDO6N8cswi3EK8cmwC+8P8E8wCzHL8s0xTvKOccvvkGVaKF3o3CeYbdWvk+6R8lA6BfpEs4mvka6VbVZulLPOdI6xkK4Rr5Hmk+TbqpQuzazPcA7uj6lYLlixj6/L8081SXTKNEpvSnRJM4l3x24N8I0szqeZ6Jsom6ibqNbo16jb5tfm2KnZJta2SrRLeoU8g/vD/AM7hCZVY1rnXiaeYxhtWPQONM3wkK7R8BNjnKqU8kwsTa3Pbk7uzydU79hzjK/NtEo0yrXJtEpvinMI9Eh3iC8OsUrqkqbap1vo3ChbqVfpFqia5tlnmSrXZtdzyviJfMN8A/zDvEO7hGSbA=="
            }
        ],
        "context": [
            {
                "label": "Clean recitation (kept)",
                "position": "before",
                "segments": [
                    {
                        "segment_uid": "failed_intentional_dup-ctx0",
                        "time_start": 1013073,
                        "time_end": 1028439,
                        "matched_ref": "14:46:1-14:46:12",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_dup.mp3"
                    }
                ]
            }
        ]
    },
    "failed_intentional_retry": {
        "id": "failed_intentional_retry",
        "title": "Bad attempt, then a retry",
        "description": "A flawed first attempt at 11:10; the reciter re-recited it cleanly, so the first is marked failed.",
        "render": "history_op",
        "chapter": 11,
        "clip_base_ms": 277915,
        "operations": [
            {
                "op_id": "98bf6eda-eecf-43c6-8d1b-5789a2d59d0d",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "1199e1a9-3307-5b66-830b-8f1864bc3be8",
                        "time_start": 278165,
                        "time_end": 283465,
                        "matched_ref": "11:10:11-11:10:12",
                        "confidence": 0.73,
                        "audio_url": "/guide-audio/failed_intentional_retry.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "1199e1a9-3307-5b66-830b-8f1864bc3be8",
                        "time_start": 278165,
                        "time_end": 283465,
                        "matched_ref": "",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_retry.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "98bf6eda-eecf-43c6-8d1b-5789a2d59d0d",
                "url": "/guide-audio/failed_intentional_retry.mp3",
                "start_ms": 277915,
                "end_ms": 299440,
                "bps": 10,
                "peaks_b64": "+wb4B/cF+AavOqpJ0ES7SMhD1jvDQ8M1tTy6PLo7uDe9NcAvvS+/M8QqvC/DMMQowybFI8koyiTMItAhyibSIdAi2SjTJs8n0SixPq1FtTa4L7QqryytNZhJmErTMq0/o0ulWMAg9gj3CPsG+Ab3BfgGujCqSsBEukjJQtU3w0PDM7U8uDy6Org3vTXAL70vvzPCK7wvxDDEKsQmxSPFKMojyiLQHsol0iHQItEo0ybPJ9EmuTytRbU1uC+0JrErrTWYRZhKqT+4PaNLpFfAI/YK9gj7BvkH9wb4Brwvq0ivQ7tHw0bTN8NEwzW1O7g8ujq4N7w2wTS8LL4zvyu8L8gvxC3NJsMjxSXMKMoi0B7KJtMd0CLRKNMmzyfQJrgsrUW1OLgvtSaxKa00o0WXSqNDxTekS6VYxim1P+cdyyjEKc8r0zDLLdIrzynSKs0szB7LI8wfzSPPINIh0SLNIdEczRrPH8wfvyW9JssfoUmcSKw4wDewN604sTapPq84tjmvPLUxrjSyNbI0sTOuM7cvsjCvMrYwrjqtLq0z8w30DfYS9RD0DPkL9gn3Cg=="
            }
        ],
        "context": [
            {
                "label": "Clean re-recitation (kept)",
                "position": "after",
                "segments": [
                    {
                        "segment_uid": "failed_intentional_retry-ctx0",
                        "time_start": 288825,
                        "time_end": 299190,
                        "matched_ref": "11:10:11-11:10:13",
                        "confidence": 0.95,
                        "audio_url": "/guide-audio/failed_intentional_retry.mp3"
                    }
                ]
            }
        ]
    },
    "failed_intentional_split": {
        "id": "failed_intentional_split",
        "title": "Stutter in the middle",
        "description": "The reciter stumbled mid-verse; the clean head and tail are kept and the stuttered middle is carved out and marked failed.",
        "render": "edit_chain",
        "chapter": 9,
        "clip_base_ms": 2864389,
        "operations": [
            {
                "op_id": "7e35b6ee-2a2a-4dba-a53d-1606660bb102",
                "op_type": "split_segment",
                "targets_before": [
                    {
                        "segment_uid": "afe5c1cf-c69a-540f-9a74-718d1db29bdd",
                        "time_start": 2864639,
                        "time_end": 2884682,
                        "matched_ref": "9:126:1-9:126:16",
                        "confidence": 0.92,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "afe5c1cf-c69a-540f-9a74-718d1db29bdd",
                        "time_start": 2864639,
                        "time_end": 2876469,
                        "matched_ref": "9:126:1-9:126:15",
                        "confidence": 0.92,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    },
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2876469,
                        "time_end": 2884682,
                        "matched_ref": "9:126:10-9:126:16",
                        "confidence": 0.92,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ]
            },
            {
                "op_id": "16577df4-a852-4afe-9ece-861345af94ff",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "afe5c1cf-c69a-540f-9a74-718d1db29bdd",
                        "time_start": 2864639,
                        "time_end": 2876469,
                        "matched_ref": "9:126:1-9:126:15",
                        "confidence": 0.92,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "afe5c1cf-c69a-540f-9a74-718d1db29bdd",
                        "time_start": 2864639,
                        "time_end": 2876469,
                        "matched_ref": "9:126:1-9:126:15",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ]
            },
            {
                "op_id": "8ba33847-6e45-4923-8ce3-a7232e92495d",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2876469,
                        "time_end": 2884682,
                        "matched_ref": "9:126:10-9:126:16",
                        "confidence": 0.92,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2876469,
                        "time_end": 2884682,
                        "matched_ref": "9:126:16-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ]
            },
            {
                "op_id": "cfaece6d-779f-474f-94cd-4a44732f6124",
                "op_type": "trim_segment",
                "targets_before": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2876469,
                        "time_end": 2884682,
                        "matched_ref": "9:126:16-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2877890,
                        "time_end": 2884682,
                        "matched_ref": "9:126:16-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ]
            },
            {
                "op_id": "fbe42ff8-a5a1-499e-9d71-e9333eeab4bd",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2877890,
                        "time_end": 2884682,
                        "matched_ref": "9:126:16-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2877890,
                        "time_end": 2884682,
                        "matched_ref": "9:126:11-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ]
            },
            {
                "op_id": "166449b6-1ce7-4e22-87de-95fe86c21a3e",
                "op_type": "trim_segment",
                "targets_before": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2877890,
                        "time_end": 2884682,
                        "matched_ref": "9:126:11-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2876469,
                        "time_end": 2884682,
                        "matched_ref": "9:126:11-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ]
            },
            {
                "op_id": "091e03d1-86ac-4d06-b1ad-6bed37256b6b",
                "op_type": "split_segment",
                "targets_before": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2876469,
                        "time_end": 2884682,
                        "matched_ref": "9:126:11-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2876469,
                        "time_end": 2877860,
                        "matched_ref": "9:126:11-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    },
                    {
                        "segment_uid": "563c68d1-f5a8-4a08-84c3-a1d5f6d1ce41",
                        "time_start": 2877860,
                        "time_end": 2884682,
                        "matched_ref": "9:126:11-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ]
            },
            {
                "op_id": "6dfef789-e681-421b-b339-1340a23c145c",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2876469,
                        "time_end": 2877860,
                        "matched_ref": "9:126:11-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2876469,
                        "time_end": 2877860,
                        "matched_ref": "9:126:11-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ]
            },
            {
                "op_id": "c10ddf21-9a45-45a1-b924-c209eb5d8284",
                "op_type": "confirm_reference",
                "targets_before": [
                    {
                        "segment_uid": "563c68d1-f5a8-4a08-84c3-a1d5f6d1ce41",
                        "time_start": 2877860,
                        "time_end": 2884682,
                        "matched_ref": "9:126:11-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "563c68d1-f5a8-4a08-84c3-a1d5f6d1ce41",
                        "time_start": 2877860,
                        "time_end": 2884682,
                        "matched_ref": "9:126:11-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ]
            },
            {
                "op_id": "ae4d5bed-862c-4d1e-80ec-ee5c5992e052",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2876469,
                        "time_end": 2877860,
                        "matched_ref": "9:126:11-9:126:16",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "c684aeb3-1c69-4736-8aa4-1947ea4a15af",
                        "time_start": 2876469,
                        "time_end": 2877860,
                        "matched_ref": "",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_intentional_split.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "7e35b6ee-2a2a-4dba-a53d-1606660bb102",
                "url": "/guide-audio/failed_intentional_split.mp3",
                "start_ms": 2864389,
                "end_ms": 2884932,
                "bps": 10,
                "peaks_b64": "8Q/3Cu8QjlqBf4F/gX+Bf5d8hX+Bf4V/g3Sca8A8q13AQswtsFnFPr01wTHGL8MwyC2uSLFUvV25PdAt0SfBKukU8BSBe5NdwD7AP8g7pVS1Q9ApzC/OLcYoxx/DKdAqyyS2N5FqunioaKVso3y1Tbs9wjjBPbxCvDu3VJ1lklOoPYFsj2qEeJJwzTDRKK9Rl3++PcNAtFGsVZ1BkmKUV4F5qEWzLsIz0CO9McwozSbRIs0ozCnIK6k/lFqoToFjgXaBdoF3hWrfIsEuyTnEOMYutTG1MbE9tTulRatZjlqgRpxmjliHWcg+sT3BNr8ztzqSXaxP3ByOb4d02iLuFKNXk1rnIIN5pUPFLcQy3By9MMwozifSJcon0CjILKdBl1eBZJJcgXiEe4F6hG/WJMEuyTnFNdQhtTKyPLM9tTymWaZWkFuuRJ1khluVWMk+sjvCNr8zmlOTXLBO3RuFcZ9W6xnvE9Mpok6UTqs2skOqTbZAuT28OrBHr0OwQahQqkqoTKZXwizEJeMT7hPvDfMM9Qr1CfgJkWw="
            }
        ]
    },
    "basmala_added_voice": {
        "id": "basmala_added_voice",
        "title": "Basmala in a different voice",
        "description": "The Fatiha basmala here was a generic insert, not the reciter — deleted. If it is in the reciter voice, keep it.",
        "render": "history_op",
        "chapter": 1,
        "clip_base_ms": 3620,
        "operations": [
            {
                "op_id": "e590560f-31bb-4f09-b935-f68be9ae87df",
                "op_type": "delete_segment",
                "targets_before": [
                    {
                        "segment_uid": "019d68c7-748c-7ecc-90e5-98054fa09eba",
                        "time_start": 3870,
                        "time_end": 6290,
                        "matched_ref": "1:1:1-1:1:4",
                        "confidence": 1,
                        "audio_url": "/guide-audio/basmala_added_voice.mp3"
                    }
                ],
                "targets_after": []
            }
        ],
        "peaks": [
            {
                "op_id": "e590560f-31bb-4f09-b935-f68be9ae87df",
                "url": "/guide-audio/basmala_added_voice.mp3",
                "start_ms": 3620,
                "end_ms": 6540,
                "bps": 10,
                "peaks_b64": "/wH/AfkH9RH9A/QN8BX0Ee0h6CbuHPgO9xT3HOYq+AXyHfAh7yL2E/gV8hv3DvUQ9Q75CPsK/QT/AQ=="
            }
        ]
    },
    "amin_trim": {
        "id": "amin_trim",
        "title": "Partial Amin after Al-Fatiha",
        "description": "A trailing Amin trimmed off the last verse.",
        "render": "history_op",
        "chapter": 1,
        "clip_base_ms": 23866,
        "operations": [
            {
                "op_id": "02ed0abf-b2a7-45c7-bc23-ecaaa800c666",
                "op_type": "trim_segment",
                "targets_before": [
                    {
                        "segment_uid": "0bf7bd7e-92be-5ad9-9336-7a3d5b0c11d6",
                        "time_start": 24116,
                        "time_end": 32835,
                        "matched_ref": "1:7:5-1:7:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/amin_trim.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "0bf7bd7e-92be-5ad9-9336-7a3d5b0c11d6",
                        "time_start": 24116,
                        "time_end": 32485,
                        "matched_ref": "1:7:5-1:7:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/amin_trim.mp3"
                    }
                ]
            },
            {
                "op_id": "882ad073-2996-4151-a755-e29c09b3314a",
                "op_type": "trim_segment",
                "targets_before": [
                    {
                        "segment_uid": "0bf7bd7e-92be-5ad9-9336-7a3d5b0c11d6",
                        "time_start": 24116,
                        "time_end": 32485,
                        "matched_ref": "1:7:5-1:7:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/amin_trim.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "0bf7bd7e-92be-5ad9-9336-7a3d5b0c11d6",
                        "time_start": 24116,
                        "time_end": 32435,
                        "matched_ref": "1:7:5-1:7:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/amin_trim.mp3"
                    }
                ]
            },
            {
                "op_id": "b380499b-c3ce-4776-81cc-721d1839beae",
                "op_type": "trim_segment",
                "targets_before": [
                    {
                        "segment_uid": "0bf7bd7e-92be-5ad9-9336-7a3d5b0c11d6",
                        "time_start": 24116,
                        "time_end": 32435,
                        "matched_ref": "1:7:5-1:7:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/amin_trim.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "0bf7bd7e-92be-5ad9-9336-7a3d5b0c11d6",
                        "time_start": 24116,
                        "time_end": 32335,
                        "matched_ref": "1:7:5-1:7:9",
                        "confidence": 1,
                        "audio_url": "/guide-audio/amin_trim.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "02ed0abf-b2a7-45c7-bc23-ecaaa800c666",
                "url": "/guide-audio/amin_trim.mp3",
                "start_ms": 23866,
                "end_ms": 33085,
                "bps": 10,
                "peaks_b64": "9Az3CfgG6Q3cJN0j2SDeI+Ua4BnmE+gd3iTcKeEiyy6wLNEn2iPeGuEc4RfoEugU6RPjFOMY6xLwDvcI7g7kFOAZ2R7NKcwpziTKKcwr0ifFLM4qyC7JJdIi1C3fGeEb4xfpF+YW5BLnF+gV5RHmGOcW4xvgHOIf4SDTI9sf3xrRIOIZ3yHpHekX6RPiHOQY6RbnHOId4RzjHeMf2SHcHuIf6hLiGuwT7w/2C/QM9A/wEu0T8RPtFQ=="
            }
        ]
    },
    "missing_fill_extend": {
        "id": "missing_fill_extend",
        "title": "Fill, then extend the audio",
        "description": "Auto-fill alone fell short: the word is added and the boundary extended to cover its audio.",
        "render": "history_op",
        "chapter": 99,
        "clip_base_ms": 33865,
        "operations": [
            {
                "op_id": "385729b1-e79d-4610-a111-b438fe586e3d",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "019d888a-0e73-7acb-8ba6-251d4b72860d",
                        "time_start": 34115,
                        "time_end": 40030,
                        "matched_ref": "99:8:1-99:8:5",
                        "confidence": 0.96,
                        "audio_url": "/guide-audio/missing_fill_extend.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "019d888a-0e73-7acb-8ba6-251d4b72860d",
                        "time_start": 34115,
                        "time_end": 40030,
                        "matched_ref": "99:8:1-99:8:6",
                        "confidence": 1,
                        "audio_url": "/guide-audio/missing_fill_extend.mp3"
                    }
                ]
            },
            {
                "op_id": "d1b80701-12c1-44f7-9350-8df659e1fd4d",
                "op_type": "trim_segment",
                "targets_before": [
                    {
                        "segment_uid": "019d888a-0e73-7acb-8ba6-251d4b72860d",
                        "time_start": 34115,
                        "time_end": 40030,
                        "matched_ref": "99:8:1-99:8:6",
                        "confidence": 1,
                        "audio_url": "/guide-audio/missing_fill_extend.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "019d888a-0e73-7acb-8ba6-251d4b72860d",
                        "time_start": 34115,
                        "time_end": 40990,
                        "matched_ref": "99:8:1-99:8:6",
                        "confidence": 1,
                        "audio_url": "/guide-audio/missing_fill_extend.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "385729b1-e79d-4610-a111-b438fe586e3d",
                "url": "/guide-audio/missing_fill_extend.mp3",
                "start_ms": 33865,
                "end_ms": 41240,
                "bps": 10,
                "peaks_b64": "3hrtFO4Ok3+Bf4Z9mn+eaq5RolSfWalNll2qW7RQtkyYbIF/gX+Sf6t/hH+6Rc8tzTbSIt4f4jeBf4F/gX+3W6t0q2K1f8c4yFKOf9IovVS1T608uzezPsU2yS3FLc8m3SvCR69kzS3ROqNnv1HcJ9op3SjYKdMr0j+1Zq1sj3rLN+sW8A/zDvcI9gj5CAAAAAA="
            }
        ]
    },
    "failed_recover_word": {
        "id": "failed_recover_word",
        "title": "Word not detected",
        "description": "A word the model missed entirely; the audio is clean, so give it its reference.",
        "render": "history_op",
        "chapter": 45,
        "clip_base_ms": 594322,
        "operations": [
            {
                "op_id": "dc01ad4a-a7b9-4cdf-aa4d-71d864c1aa82",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "5f7a7b10-07ff-5bc5-b271-77c45129e7ef",
                        "time_start": 594572,
                        "time_end": 596933,
                        "matched_ref": "",
                        "confidence": 0,
                        "audio_url": "/guide-audio/failed_recover_word.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "5f7a7b10-07ff-5bc5-b271-77c45129e7ef",
                        "time_start": 594572,
                        "time_end": 596933,
                        "matched_ref": "45:35:10-45:35:10",
                        "confidence": 1,
                        "audio_url": "/guide-audio/failed_recover_word.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "dc01ad4a-a7b9-4cdf-aa4d-71d864c1aa82",
                "url": "/guide-audio/failed_recover_word.mp3",
                "start_ms": 594322,
                "end_ms": 597183,
                "bps": 10,
                "peaks_b64": "6w/qEOwPszyhUsonyiu+McUnvCi/LdEj3CHYGdga1xjUGtYZ3RvVH9cg0SHQK+sV7RfyDLg5pj8="
            }
        ]
    },
    "lowconf_wrong_word": {
        "id": "lowconf_wrong_word",
        "title": "Wrong word, low confidence",
        "description": "The model matched this audio to the wrong verse; low confidence flagged it and it was recovered to 25:59:14.",
        "render": "history_op",
        "chapter": 25,
        "clip_base_ms": 929242,
        "operations": [
            {
                "op_id": "93d7b75a-f930-4037-91df-2b34d3a9b81d",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "84f2e0fc-a6e5-500b-b98d-d63fd07e9899",
                        "time_start": 932912,
                        "time_end": 935828,
                        "matched_ref": "25:60:5-25:60:5",
                        "confidence": 0.67,
                        "audio_url": "/guide-audio/lowconf_wrong_word.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "84f2e0fc-a6e5-500b-b98d-d63fd07e9899",
                        "time_start": 932912,
                        "time_end": 935828,
                        "matched_ref": "25:60:1-25:60:13",
                        "confidence": 1,
                        "audio_url": "/guide-audio/lowconf_wrong_word.mp3"
                    }
                ]
            },
            {
                "op_id": "e2fa7d3d-5c70-4de8-a127-ca18796ea17a",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "84f2e0fc-a6e5-500b-b98d-d63fd07e9899",
                        "time_start": 932912,
                        "time_end": 935828,
                        "matched_ref": "25:60:1-25:60:13",
                        "confidence": 1,
                        "audio_url": "/guide-audio/lowconf_wrong_word.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "84f2e0fc-a6e5-500b-b98d-d63fd07e9899",
                        "time_start": 932912,
                        "time_end": 935828,
                        "matched_ref": "25:59:1-25:59:17",
                        "confidence": 1,
                        "audio_url": "/guide-audio/lowconf_wrong_word.mp3"
                    }
                ]
            },
            {
                "op_id": "0967f785-ce72-4234-b307-0039ab84345c",
                "op_type": "edit_reference",
                "targets_before": [
                    {
                        "segment_uid": "84f2e0fc-a6e5-500b-b98d-d63fd07e9899",
                        "time_start": 932912,
                        "time_end": 935828,
                        "matched_ref": "25:59:1-25:59:17",
                        "confidence": 1,
                        "audio_url": "/guide-audio/lowconf_wrong_word.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "84f2e0fc-a6e5-500b-b98d-d63fd07e9899",
                        "time_start": 932912,
                        "time_end": 935828,
                        "matched_ref": "25:59:14-25:59:14",
                        "confidence": 1,
                        "audio_url": "/guide-audio/lowconf_wrong_word.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "93d7b75a-f930-4037-91df-2b34d3a9b81d",
                "url": "/guide-audio/lowconf_wrong_word.mp3",
                "start_ms": 929242,
                "end_ms": 936078,
                "bps": 10,
                "peaks_b64": "8xTrF/MN5CTbJ+Ya7xruHegY3R/ZJdsj1yi/J70u1yj0DdIwzTLMPcFAvFC9UbZNuEmySLg/uEe2O65grWCxVcY52DfiGNwf5B6tXaRfqVW4WLBZslKzUsoxzSvJMsU7xT7FO8g7yTzPN8hFzUXLN803yD3ORc9DwELOKdYs3CXxEukQsV2kWQ=="
            }
        ],
        "context": [
            {
                "label": "Preceding words (25:59:10–13)",
                "position": "before",
                "segments": [
                    {
                        "segment_uid": "lowconf_wrong_word-ctx0",
                        "time_start": 929492,
                        "time_end": 932872,
                        "matched_ref": "25:59:10-25:59:13",
                        "confidence": 0.95,
                        "audio_url": "/guide-audio/lowconf_wrong_word.mp3"
                    }
                ]
            }
        ]
    },
    "boundary_cut_early": {
        "id": "boundary_cut_early",
        "title": "Cut off early",
        "description": "The segment ended before the word finished; trimming the boundary fixes both this and its low-confidence flag.",
        "render": "history_op",
        "chapter": 3,
        "clip_base_ms": 1948106,
        "operations": [
            {
                "op_id": "2e084c11-5037-444f-9de5-677ab8e161fd",
                "op_type": "trim_segment",
                "targets_before": [
                    {
                        "segment_uid": "3b53d81e-5f4e-572d-85f9-4dba8d9db66d",
                        "time_start": 1948356,
                        "time_end": 1958185,
                        "matched_ref": "3:131:1-3:131:5",
                        "confidence": 0.79,
                        "audio_url": "/guide-audio/boundary_cut_early.mp3"
                    }
                ],
                "targets_after": [
                    {
                        "segment_uid": "3b53d81e-5f4e-572d-85f9-4dba8d9db66d",
                        "time_start": 1948356,
                        "time_end": 1953220,
                        "matched_ref": "3:131:1-3:131:5",
                        "confidence": 1,
                        "audio_url": "/guide-audio/boundary_cut_early.mp3"
                    }
                ]
            }
        ],
        "peaks": [
            {
                "op_id": "2e084c11-5037-444f-9de5-677ab8e161fd",
                "url": "/guide-audio/boundary_cut_early.mp3",
                "start_ms": 1948106,
                "end_ms": 1958435,
                "bps": 10,
                "peaks_b64": "+wT9A/0C7BHvDvwE8RD1CvQM9Qj2B/QJ9Aj2CO8P7g3zC/ML8wzwDvMJ8g7zDvUN8w31CvIN9AvzDfQN8A3qEfAM+QXuDfEJ9wnzDvYL7RTtEO8O8gzzD/MO8BDwDfEN9Ar1C/cH6xH4DvwE8Q70CvQM9An2B/YJ9Qf2B+4Q7g30C/EL8g3xD/gH8g7xDvQM8w3zC/QN9AzzDfMM8Q3pFPAM+gXuDvcH9wjzD/YL7RHsEvAO8Q3yDvIQ8BDyDPEO9Av2C/YG/gL9A/MR7hA="
            }
        ]
    }
} as const;

export const guideExamples: Readonly<Record<string, GuideExample>> =
    Object.freeze(data as unknown as Record<string, GuideExample>);

export function getGuideExample(id: string): GuideExample | null {
    return guideExamples[id] ?? null;
}
