#!/usr/bin/env python3
"""Regenerate TypeScript types from Pydantic schemas.

Drives ``pydantic-to-typescript`` over the shared schemas at
``scripts/lib/schemas/`` and writes the generated TypeScript interface
file to ``inspector/frontend/src/lib/types/generated/schemas.ts``.

Run after touching any module under ``scripts/lib/schemas/``::

    python inspector/scripts/regen_fe_types.py

The generated file is committed to git. CI runs the same command and
fails the build via ``git diff --exit-code`` if the committed file
diverges from regeneration — this is the structural fix that stops
backend Pydantic models from drifting against FE TypeScript types.

Migration #5 (``docs/reference/data-migrations.md`` §5) introduces the
codegen pipeline.

Requirements:
- ``pydantic-to-typescript`` Python package (pinned in
  ``inspector/requirements-dev.txt``).
- ``json-schema-to-typescript`` npm package (pinned in
  ``inspector/frontend/package.json``'s ``devDependencies``).
"""
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUTPUT = REPO / "inspector" / "frontend" / "src" / "lib" / "types" / "generated" / "schemas.ts"
FRONTEND = REPO / "inspector" / "frontend"
SCHEMAS_MODULE = "scripts.lib.schemas.fe_types"


def _resolve_json2ts() -> Path:
    """Locate the ``json2ts`` CLI shipped by the npm package.

    Prefer the FE's local ``node_modules/.bin/json2ts`` so we use the
    exact version pinned in ``package.json``; fall back to ``$PATH``.
    """
    local = FRONTEND / "node_modules" / ".bin" / "json2ts"
    if local.is_file():
        return local
    on_path = shutil.which("json2ts")
    if on_path:
        return Path(on_path)
    raise SystemExit(
        "json2ts CLI not found. Run `npm install --save-dev "
        "json-schema-to-typescript` inside inspector/frontend, or install "
        "globally with `npm install -g json-schema-to-typescript`."
    )


def _ensure_pydantic_to_typescript() -> None:
    try:
        import pydantic2ts  # noqa: F401
    except ImportError as exc:
        raise SystemExit(
            "pydantic-to-typescript not installed. Run "
            "`pip install -r inspector/requirements-dev.txt` first."
        ) from exc


def main() -> int:
    _ensure_pydantic_to_typescript()
    json2ts = _resolve_json2ts()

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    # pydantic2ts.generate_typescript_defs takes a Python module path,
    # introspects every BaseModel subclass, exports their JSON schemas
    # via Pydantic v2's `.model_json_schema()`, then shells out to json2ts.
    # The repo root must be on sys.path so the `scripts.lib.schemas` import
    # resolves.
    if str(REPO) not in sys.path:
        sys.path.insert(0, str(REPO))

    from pydantic2ts import generate_typescript_defs

    generate_typescript_defs(
        module=SCHEMAS_MODULE,
        output=str(OUTPUT),
        json2ts_cmd=str(json2ts),
    )

    # Stamp a header so anyone diffing the file sees the regen command.
    text = OUTPUT.read_text(encoding="utf-8")
    header = (
        "/* eslint-disable */\n"
        "// AUTOGENERATED by inspector/scripts/regen_fe_types.py — DO NOT EDIT.\n"
        "// Regenerate after touching scripts/lib/schemas/:\n"
        "//   python inspector/scripts/regen_fe_types.py\n"
        "// CI fails via `git diff --exit-code` on this path if out of sync.\n"
        "// See docs/reference/data-migrations.md §5.\n\n"
    )
    if not text.startswith("/* eslint-disable */"):
        OUTPUT.write_text(header + text, encoding="utf-8")

    print(f"Generated {OUTPUT.relative_to(REPO)} ({OUTPUT.stat().st_size} B)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
